version: "4.3"
services:
  alex-dolfinx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shared:/home
    working_dir: /home
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "10.0"
    #       memory: 24G
