version: "3"
services:
  alex-dolfinx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./shared:/home
    working_dir: /home
    deploy:
      resources:
        limits:
          cpus: 10
          memory: 24G
